DemoWeb/DemoWeb/Controllers/InventoryController.cs
using Demo.Data.Models;
using Demo.Data.ViewModels;
using Demo.Service;
using Demo.Service.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoWeb.Controllers
{
    [Authorize]
    public class InventoryController : Controller
    {
        private IInventoryService inventoryService;
        private IMaterialService materialService;
        private IUserService userService;


        public InventoryController()
        {
            this.inventoryService = new InventoryService();
            this.materialService = new MaterialService();
            this.userService = new UserService();
        }

        // GET: Inventory
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 取得庫存資料
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult JsonGetListData()
        {
            try
            {
                var temp = this.inventoryService.GetAllHaveInfo().ToList();
                var model = new InventoryViewModel() { ListData = temp };
                return Json(new ReData { Success = true, Data = model }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new ReData { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// 取得物料選單資料
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult JsonGetMaterialSelect()
        {
            try
            {
                var temp = this.materialService.GetAll().ToList();
                return Json(new ReData { Success = true, Data = temp }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new ReData { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// 物料入庫
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult StockIn(Inventory item)
        {
            try
            {
                item.Creater = this.userService.GetIDByAccount(User.Identity.Name);
                item.LastEditor = item.Creater;
                this.inventoryService.StockIn(item);
                return Json(new ReData { Success = true });
            }
            catch (Exception ex)
            {
                return Json(new ReData { Success = false, Message = ex.Message });
            }
        }

        /// <summary>
        /// 物料出庫
        /// </summary>
        /// <param name="item"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult StockOut(Inventory item)
        {
            try
            {
                item.LastEditor = this.userService.GetIDByAccount(User.Identity.Name);
                this.inventoryService.StockOut(item);
                return Json(new ReData { Success = true });
            }
            catch (Exception ex)
            {
                return Json(new ReData { Success = false, Message = ex.Message });
            }
        }
    }
}

DemoWeb/DemoWeb/Controllers/MaterialController.cs
using Demo.Data.Models;
using Demo.Data.ViewModels;
using Demo.Service;
using Demo.Service.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoWeb.Controllers
{
    [Authorize]
    public class MaterialController : Controller
    {
        private IMaterialService materialService;
        private IUserService userService;

        public MaterialController()
        {
            this.materialService = new MaterialService();
            this.userService = new UserService();
        }


        // GET: Material
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 取得所有物料資料
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult JsonGetListData()
        {
            try
            {
                var temp = this.materialService.GetAllHaveInfo().ToList();
                var model = new MaterialViewModel() { ListData = temp };
                return Json(new ReData { Success = true, Data = model }, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                return Json(new ReData { Success = false, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// 新增物料
        /// </summary>
        /// <param name="material"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult JsonCreate(Material material)
        {
            try
            {
                material.Creater = this.userService.GetIDByAccount(User.Identity.Name);
                material.LastEditor = material.Creater;
                this.materialService.Create(material);
                return Json(new ReData { Success = true });
            }
            catch (Exception ex)
            {
                return Json(new ReData { Success = false, Message = ex.Message });
            }
        }

        /// <summary>
        /// 物料變更
        /// </summary>
        /// <param name="material"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult JsonUpdate(Material material)
        {
            try
            {
                material.LastEditor = this.userService.GetIDByAccount(User.Identity.Name);
                this.materialService.Update(material);
                return Json(new ReData { Success = true });
            }
            catch (Exception ex)
            {
                return Json(new ReData { Success = false, Message = ex.Message });
            }
        }

        /// <summary>
        /// 物料刪除
        /// </summary>
        /// <param name="material"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult JsonDelete(Material material)
        {
            try
            {
                this.materialService.Delete(material);
                return Json(new ReData { Success = true });
            }
            catch (Exception ex)
            {
                return Json(new ReData { Success = false, Message = ex.Message });
            }
        }
    }
}

DemoWeb/DemoWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        @*Reference : https://getbootstrap.com/docs/4.5/examples/carousel/ *@
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            @Html.ActionLink("Demo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">

                @if (User.Identity.IsAuthenticated)
                {

                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            @Html.ActionLink("首頁", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("物料管理", "Index", "Material", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("物料進出庫", "Index", "Inventory", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item ml-auto">
                            <span class="nav-link">User</span>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link" href="@Url.Action("Logout", "Login")" title="登出">
                                <i class="fas fa-sign-out-alt"></i>
                            </a>
                        </li>
                    </ul>
                }
            </div>
        </nav>
    </header>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/tsTool")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/vue")
    @RenderSection("scripts", required: false)
</body>
</html>